### ISSUE TITLE
creating a GridDyn project group

### ISSUE THREAD

**Issue by phlptp** [LLNL/GridDyn#26]
I am starting to wonder if it might be a good idea to create project group for GridDyn, so we could have examples as a separate repo and some of the other libraries split out from GridDyn in a group?  I am not sure if we would use that as the main on or this one as the main one and miror it?  

@nightlark @mcneish1   What do you think?

**Comment by nightlark** [comment]
The biggest benefit to using this as the main repo is that projects under the LLNL github organization have a much higher number of concurrent builds.

**Comment by phlptp** [comment]
That is probably a good point to keep the main repo as the current one and Mirror it in a separate project group.

**Comment by phlptp** [comment]
@nightlark the griddyn user on github?  is that linked to the griddyn email address or is that someone else?

**Comment by nightlark** [comment]
That's linked to the griddyn email address. I think the user is part of the LLNL/GridDyn repo, for use with appveyor.

**Comment by phlptp** [comment]
could we make some other repos eventually off of that user?  Or should we make that into an organization.   It would be nice to have the organization be named griddyn?

**Comment by nightlark** [comment]
We could transform it into an organization; I don't know how that would affect appveyor -- we could rename the griddyn account to griddyn-bot or similar to be used as the account for any automated actions in the future by Travis (ex build + push docs)

**Comment by phlptp** [comment]
Lets say we are going to want someplace sensible to put some supporting libraries (examples, use-cases, large-tests, and break out some supporting libraries).  What would be your recommendation for how best to do that and what organization name/user to place them under.

**Comment by nightlark** [comment]
Probably a griddyn organization would be consistent with how other projects at LLNL (mfem, rose) and outside do things.

**Comment by mcneish1** [comment]
https://github.com/LLNL/GridDyn/projects ? That can reference other repositories as needed, and we can always move, say, LLNL/GridDynExamples to GridDyn/GridDynExamples later if needed.

My only real concern with making an organization (if making a github project isn't what we want to do) is the other LLNL organizations (mfem, rose, spack, etc.) all have much bigger communities

**Comment by phlptp** [comment]
I suppose there are a few groups that multiple projects under the LLNL organization.  Maybe I will ask Ian if he has a preference on this topic.

**Comment by phlptp** [comment]
After Chatting with Ian, I think we will due any related repos as part of the LLNL organization,  if/when the time comes where LLNL is not the primary on the organization we will evaluate what to do at that point.
