### ISSUE TITLE
GridDyn autobuild on Windows

### ISSUE THREAD

**Issue by nightlark** [LLNL/GridDyn#35]
Both AUTOBUILD_SuiteSparse and AUTOBUILD_KLU need to be given to GridDyn to make SuiteSparse get autobuilt (AUTOBUILD_SuiteSparse didn't show up in the list of options with the initial configuration on Windows). Is the behavior of needing to provide both of these options intended?

**Comment by nightlark** [comment]
Some context, I let autobuild create the dependencies in a release configuration on Windows, and then created a fresh build folder with CMAKE_PREFIX_PATH set to the libs folder in the previous build directory. The previously built copy of zlib and minizip don't get detected (it autobuilds them again).

Minizip also has an error on Windows, probably caused by CMAKE_BUILD_TYPE not being set.
```
CMake Error at config/cmake/buildMiniZip.cmake:6 (if):
  if given arguments:

    "IN_LIST" "valid_btypes"

  Unknown arguments specified
Call Stack (most recent call first):
  src/utilities/CMakeLists.txt:104 (build_minizip)
```

**Comment by mcneish1** [comment]
I'm in favor of dropping one or the other. Think I'd prefer keeping AUTOBUILD_KLU and adding AUTOBUILD_* for other parts of SuiteSparse as needed.

**Comment by phlptp** [comment]
I think we should drop one,  but KLU pretty much needs most of suitesparse so I am not sure which one to drop

**Comment by phlptp** [comment]
Can you check with the latest commit?

**Comment by nightlark** [comment]
That feels a lot smoother getting suitesparse/klu autobuilt as the default behavior. The minizip error is also gone.
