### ISSUE TITLE
failure in the valgrind run

### ISSUE THREAD

**Issue by phlptp** [LLNL/GridDyn#41]
There appears to be something wrong with the valgrind=true run for GridDyn
[link](https://travis-ci.org/LLNL/GridDyn/jobs/429907183) on Travis.

**Comment by nightlark** [comment]
A cmake segfault?

**Comment by phlptp** [comment]
I would doubt it but you never know.  I thought it was working earlier so not sure what happened.

**Comment by nightlark** [comment]
The build started failing on the nightly builds one day, with no change from what was built the previous day. I wiped the cache for the cmake_update branch and that seems to have fixed it -- somehow, the old cache was causing the cmake command to segfault.

**Comment by mcneish1** [comment]
That might have been my fault. I messed with the cache a little because of my changes to the libs folder. That still shouldn't have made cmake segfault though...

**Comment by nightlark** [comment]
It shouldn't -- I don't think I saw anything in the build history between the last nightly run that succeeded and first that failed. Maybe the cache got corrupted.

Anyway, it looks like it is working now -- last night's build was fine.
