### ISSUE TITLE
variant.hpp fails to compile with MSVC 19.15

### ISSUE THREAD

**Issue by nightlark** [LLNL/GridDyn#42]
The variant.hpp file doesn't compile with MSVC 19.15; the issue for the bug on GitHub for the third party library is: https://github.com/mpark/variant/issues/48
mpark/variant PR to disable constexpr in MSVC 2017: https://github.com/mpark/variant/pull/49

And the compiler bug report on the Visual Studio developer community can be found at: https://developercommunity.visualstudio.com/content/problem/275141/c2131-expression-did-not-evaluate-to-a-constant-fo.html (upvoting will make it more likely to get fixed sooner)

**Comment by phlptp** [comment]
Have you actually observed this issue, if so what warnings does it produce?

**Comment by nightlark** [comment]
Yes, it produces the C2131 compiler error (expression not evaluating to a constant). It only affects versions of visual studio 2017 released in the past several months.

**Comment by phlptp** [comment]
It looks like the variant has a fix that hasn't made it into the single_header version yet.  So I have updated it.  I will merge that once I get Corey's changes merged.

**Comment by nightlark** [comment]
There's been a status update on the compiler bug report -- the 16.0 release will fix it (VS2019?).
